using PrayerTime.Web.Dtos;

namespace PrayerTime.Web.Pages;

public partial class Home
{
    public BookData[] Datas = new BookData[225];
    protected override void OnInitialized()
    {
        string[] BookNames = 
        {
            "Life3.0",
            "Grokking Algorithms",
            "The Black Swan",
            "Read people like a book",
            "Clean Code",
            "Algorithms to Live by",
            "Measure What Matters",
            "Traction",
            "Empowered",
            "Deep Work",
            "Emotional Intelligence 2.0",
            "Principles",
            "Extreme Ownership",
            "Profit First",
            "Actionable Gamification",
            "Engineers’ Survival Guide",
            "Leading from Anywhere (2)",
            "The Long-Distance Leader",
            "Rocket Fuel",
            "Originals",
            "User Story Mapping",
            "Good To Great",
            "The Four Obsessions of an Extraordinary Executive",
            "The Miracle morning",
            "Alone Together",
            "Start With Why",
            "The Infinite Game",
            "Think Again",
            "Find Your Why",
            "Blockchain Wars",
            "Trillion Dollar Coach",
            "Atomic Habits",
            "Value Propostion Design",
            "Outsourcing",
            "Get A Grip",
            "Hooked",
            "Financial Intelligence",
            "Psychology of Money",
            "Smarter Faster Better",
            "Continuous Discovery Habits",
            "Contagious",
            "The New One Minute Manager",
            "Rework",
            "Blink",
            "Human Compatible",
            "Crucial Conversation",
            "Startup CXO",
            "API Design Patterns",
            "How to take smart notes",
            "Blockchain Wars",
            "Unit Testing",
            "The Book Of Why",
            "Designning Data-Intensive Applications",
            "Vested Outsourcing",
            "Outliers",
            "Code That Fits in Your Head",
            "No Rules and the Culture of Reinvention",
            "What the Heck is EOS?",
            "75+ Team Building Activities for Remote Teams",
            "Head first Design Patterns",
            "Breath",
            "Zero to One",
            "The Phoenix Project",
            "Eat That Frog",
            "Master Your Emotions",
            "The Perfect Weapon",
            "Man’s Search For Meaning",
            "Inspired",
            "The EOS Life",
            "Spatial Web",
            "Influencing Virtual Teams",
            "Merchants of Doubt",
            "Power",
            "The Ride Of A Lifetime",
            "Leaders Eat Last",
            "The Tipping Point",
            "The Lean Product Playbook",
            "The Manager’s Path",
            "Selling Outsourcing Services in the Digital Age",
            "Steve Jobs",
            "You Are a Badass",
            "Dream No Little Dreams",
            "How To Win Friends & Influence People",
            "The Intelligent Investor",
            "Antifragile",
            "Changes",
            "Blockchain Revolution",
            "Learning Domain-driven Design",
            "Elon Musk",
            "Selling Outsourcing Services",
            "The Meta-Verse",
            "Thinking Fast and Slowly",
            "12 Rules For Life",
            "LinkedIn Riches",
            "Skin in The Game",
            "Vivid Vision",
            "The Fearless Organization",
            "Who Moved My Cheese?",
            "The Bitcoin Standard",
            "Good Code, Bad Code",
            "The Brain",
            "Inside Outsourcing",
            "The Laws Of Human Nature",
            "Success is in Your Sphere",
            "The Five Dysfunctions Of A Team",
            "Why We Sleep",
            "EWTS (Exactly What To Say)",
            "Culture Driven Recruiting (2)",
            "How To Be A great Boss",
            "Benjamin Franklin",
            "Fooled By Randomness",
            "Dare To Lead",
            "Bad Blood",
            "The 7 Habits Of Highly Effective People",
            "Patterns Of Enterprise Application Architecture",
            "Cracking the Coding Interview",
            "Cracking the Coding Interview",
            "Cracking the Coding Interview",
            "Cracking the Coding Interview",
            "Cracking the Coding Interview",
            "The Leading Brain",
            "Never Split The Difference",
            "Getting Things Done",
            "Scrum",
            "Building A Story Brand",
            "Hire By Design",
            "Who Not How",
            "Business Model Generation",
            "Predictably Irrational",
            "How to Create a Mind",
            "Factfulness",
            "Homo Deus",
            "Superintelligence",
            "Clean Architecture",
            "Refactoring",
            "The Lean Startup",
            "Fundamentals of Deep Learning",
            "Quiet",
            "Process!",
            "Unique Ability 2.0 Discovery",
            "1984",
            "Give & Get (2)",
            "Powerful Phrases",
            "Talent Chooses You",
            "The Celebrity CEO",
            "You Are The Brand",
            "The 11 Laws Of Likability",
            "The Road To Wigan Pier",
            "Global Outsourcing and Offshoring",
            "Mastermind Dinners",
            "Ask Powerful Questions",
            "Giftology",
            "Give and take",
            "Beyond Order",
            "Never Eat Alone",
            "101 Tough Conversations To Have With Employees",
            "LinkedIn For Personal Branding",
            "Surrounded By Idiots",
            "Branding Pays",
            "Nuts!",
            "The 1-Page Marketing Plan",
            "Generation Z in the Workplace",
            "Sticking Points",
            "Small Giants",
            "Networking Is Not Working",
            "Risking",
            "Agile Testing",
            "Software Testing Techniques",
            "Software Test Automation",
            "How to Break Software",
            "7 Stratgies for Wealth & Happiness",
            "Sell Like a Crazy",
            "The Art of closing",
            "The challenger customer",
            "Getting to Yes/Go-giver(SAME ID)",
            "The Challenger Sale",
            "The Sales Boss",
            "How to Read a Book",
            "Purple Cow",
            "Gap Selling",
            "Friend of a Friend",
            "Super connector",
            "The Daily Stoic",
            "How to Get everything You want out of life",
            "The 22 Immutable Laws of Branding",
            "How to Become Millionaraire",
            "The Coaching Habit",
            "Sapiens",
            "Brave New World",
            "Demons",
            "Reinventing You",
            "Trust Me I’m lying",
            "Crime and Punishment",
            "How to be a Power Connector",
            "The E Myth Revisited",
            "The Seasons Of Life",
            "7 Strategies For Wealth & Happiness",
            "The Four Agreements",
            "The Thursday Murder Club",
            "Muvaffaqiyat Kaliti",
            "Temur Tuzuklari",
            "Tarixdan Bosqichli Tizim",
            "G’ordagi Olishuv",
            "Remark",
            "Uylanish Odobi",
            "Diqqat",
            "Uzun Kechalar",
            "Erkak Yeg’lagan Kun",
            "Hayolimda Bo’lding Uzun Kun",
            "Uyla va Boy Bo’l",
            "Osmondan Tushgan Pul",
            "Boy Ota va Kambag’al Ota",
            "Liderlar Kitobi",
            "Qirolichaning Yurishi",
            "Endless Referrals",
            "The Referral Engine",
            "Unstoppable Referrals",
            "The Anatomy of Buzz",
            "The Lost art of Closing",
            "English-Uzbek Dictionary 75 000 entries",
            "Super Connector",
            "The Psychology of Selling",
            "The art of Closing the Sale",
            "Unreasonable  Hospitality",
            "Influence (The Psychology of Persuasion)"
        };

        string[] Authors = 
        {
            "Max Tegmark",
            "Aditya Y. Bhargava",
            "Nassim Nicholas Taleb",
            "Patrick King",
            "Rober C.Martin",
            "Brian Christian,Tom Griffits",
            "John Doear",
            "Gino Wickman",
            "Chris Jones,Marty Cagan",
            "Cal Newport",
            "Jean Greaves,Travis Bradberry",
            "Ray Dailio",
            "Jocko Willink,Leif Babin",
            "Mike Michalowicz",
            "Yu-Kai Chou",
            "Merih Taze",
            "David Burkus",
            "Kevin Eikenberry,Wayne Turmel",
            "Gino Wickman,Mark C. Winters",
            "Adam Grant",
            "Jeff Patton",
            "Jim Collins",
            "Patrick Lencioni",
            "Hal Elrod",
            "Sherry Turkle",
            "Simon Sinek",
            "Simon Sinek",
            "Adam Grant",
            "Simon Sinek",
            "Evan McFarland",
            "Alan Eagle,Eric Schmidt,Jonathan Rosenberg",
            "James Clear",
            "Alan Smith,Alex Osterwalder,Greg Bernarda,Yves Pigneur",
            "Leslie P Willcocks,Mary Lacity,Sara Cullen",
            "Gino Wickman,Mike Paton",
            "Nir Eyal,Ryan Hoover",
            "Joe Knight,John Case,Karen Berman",
            "Morgan Housel",
            "Charles Duhigg",
            "Teresa Torres",
            "Jonah Berger",
            "Ken Blanchard,Spencer Johnson",
            "David Heinemeir Hansson,Jason Fried",
            "Malcolm Gladwell",
            "Stuart Russel",
            "Al Switzler,Emily Gregory,Joseph Grenny,Kerry Patterson,Ron McMillan",
            "Matt Blumberg,Peter M.Berkeland,Scott Dorsey",
            "JJ Geewax,Jon Skeet",
            "Sönke Ahrens",
            "Evan McFarland",
            "Vladimir Khorikov",
            "Judea Pearl",
            "Martin Kleppmann",
            "Kate Vitasek",
            "Malcolm Gladwell",
            "Mark Seemann,Robert C.Martin",
            "Erin Meyer,Reed Hastings",
            "Gino Wickman,Tom Bouwer",
            "Christopher Littlefield",
            "Bert Bates,Elisabeth Robson,Eric Freeman,Kathy Sierra",
            "James Nestor",
            "Blake Masters,Peter Thiel",
            "Gene Kim,George Spafford,Kevin Behr",
            "Brian Tracy",
            "Thibaut Meurisse",
            "David Sanger",
            "Viktor E. Frankl",
            "Marty Cagan",
            "Don Tinney,Gino Wickman",
            "Dan Mapes,Gabriel Rene",
            "Hassan Osman",
            "Erik M. Conway,Naomi Oreskes",
            "Robert Greene",
            "Robert Iger",
            "Simon Sinek",
            "Malcolm Gladwell",
            "Dan Olsen",
            "Camille Fournier",
            "Grant S.Lange",
            "Isaacson Walter",
            "Jen Sincero",
            "Clayton L. Mathile,Echo M. Garret",
            "Dale Carnegie",
            "Benjamin Graham",
            "Nassim Nicholas Taleb",
            "Michael Diettrich-Chastain",
            "Alex Tapscott,Don Tapscott",
            "Julie Lerman,Vlad Khononov",
            "Ashlee Vance",
            "Grant S. Lange",
            "Matthew Ball",
            "Daniel Kahneman",
            "Jordan B. Petterson",
            "John Nemo",
            "Nassim Nicholas Taleb",
            "Cameron Herold",
            "Amy C.Edmondson",
            "Spencer Johnson",
            "Michael Saylor,Saifedean Ammous",
            "Tom Long",
            "David Eagleman",
            "Derek Gallimore",
            "Robert Greene",
            "F. Scott Fitzgerald",
            "Patrick Lencioni",
            "Matthew Walker",
            "Phil M Jones",
            "Lee-anne Edwards",
            "Gino Wickman,Rene Boer",
            "Walter Isaacson",
            "Nassim Nicholas Taleb",
            "Brene Brown",
            "John Carreyrou",
            "Jim Collins,Stephan R. Covey",
            "Martin Fowler",
            "Gayle Laakmann McDowell",
            "Gayle Laakmann McDowell",
            "Gayle Laakmann McDowell",
            "",
            "Gayle Laakmann McDowell",
            "Friederike Fabritius,Hans W.Hagemann",
            "Chris Voss,Tahl Raz",
            "David Allen",
            "Jeff Sutherland",
            "Donald Miller",
            "Jodi Brandstetter",
            "Benjamin Hardy,Dan Sullivan",
            "Alexander Osterwalder,Yves Pigneur",
            "Dan Ariely",
            "Ray Kurzweil",
            "Anna Rosling,Hans Rosling,Ola Rosling",
            "Yuval Noah Harari",
            "Nick Bostrom",
            "Robert C.Martin",
            "Kent beck,Martin Fowler",
            "Eric Ries",
            "Joe Papa,Nikhil buduma,Nithin Buduma",
            "Susan Cain",
            "Liza Gonzalez,Mike Paton",
            "Catherine Nomura,Julia Waller,Shannon Waller",
            "George Orwell",
            "Bryan Adams,Charlotte Marshall",
            "Renee Evenson",
            "James Ellis",
            "Ramon Ray",
            "Mike Kim",
            "Michelle Tillis Lederman",
            "George Orwell",
            "Ilan Oshri,Julia Kotlarsky",
            "Jayson Gaignard",
            "Will Wise",
            "John Ruhlin",
            "Adam Grant",
            "Jordan B. Petterson",
            "Keith Ferrazzi",
            "Paul Falcone",
            "Sandra Long",
            "Thomas Erikson",
            "Karen Kang",
            "Jackie Freiberg,Kevin Freiberg",
            "Allan Dib",
            "Candace Steele Flippin",
            "Haydn Shaw",
            "Bo Burlingham",
            "Derek Coburn",
            "David Viscott",
            "Janet Gregory,Lisa Crispin",
            "Boris Beizer",
            "Dorothy Graham,Mark Fewster",
            "James A.Whitetaker",
            "Jim Rohn",
            "John Carreyrou",
            "",
            "",
            "",
            "Neil Rackham",
            "",
            "",
            "Seth Godin",
            "",
            "",
            "Ryan Paugh,Scott Gerber",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Richard Osman",
            "Deyl Karnegi",
            "",
            "Ilyosxo'ja Bekmirzayev",
            "Anvar Obidjon",
            "Erix Mariya",
            "Imom G'azzoliy",
            "Kel Nyuport",
            "O'tkir Hoshimov",
            "Rustam Jabborov",
            "Hamid Olimjon",
            "Napoleon Hill",
            "O'tkir Hoshimov",
            "Robert Kiyosaki",
            "Otabek Xasanov",
            "Uolter Tevis",
            "Bob Burg",
            "John Jantsch",
            "Steve Gordan",
            "",
            "Anthony Iannarino",
            "",
            "Ryan Paugh,Scott Gerber",
            "Brian Tracy",
            "Brian Tracy",
            "Will Guidara",
            "Robert B. Cialdini",
        };

        string[] BookTypes = 
        {
            "Personal Development",
            "Personal Development",
            "Personal Development",
            "Personal Development",
            "Engineering",
            "Engineering",
            "Leadership & Management",
            "Leadership & Management",
            "Leadership & Management",
            "Personal Development",
            "Personal Development",
            "Politics",
            "Business",
            "",
            "",
            "",
            "HR",
            "Remote Teams",
            "",
            "",
            "PM",
            "Leadership & Management",
            "Leadership & Management",
            "",
            "",
            "Personal Development",
            "",
            "",
            "",
            "Technology",
            "",
            "",
            "UX/UI design",
            "Marketing",
            "",
            "",
            "",
            "",
            "",
            "PM",
            "Leadership & Management",
            "Leadership & Management",
            "",
            "",
            "",
            "Leadership & Management",
            "Technology",
            "Engineering",
            "",
            "Technology",
            "Engineering",
            "",
            "",
            "Marketing",
            "",
            "Engineering",
            "",
            "Leadership & Management",
            "Remote Teams",
            "",
            "",
            "Business",
            "",
            "Personal Development",
            "Personal Development",
            "Philosophy",
            "",
            "PM",
            "",
            "Engineering",
            "HR",
            "",
            "",
            "",
            "Leadership & Management",
            "",
            "PM",
            "Leadership & Management",
            "Marketing",
            "Autobiography",
            "",
            "",
            "Personal Development",
            "Business",
            "",
            "",
            "Technology",
            "",
            "Autobiography",
            "Marketing",
            "",
            "",
            "",
            "Marketing",
            "Leadership & Management",
            "Leadership & Management",
            "Leadership & Management",
            "Novel",
            "Technology",
            "Engineering",
            "Science",
            "Marketing",
            "Philosophy",
            "Novel",
            "Leadership & Management",
            "Science",
            "Personal Development",
            "HR",
            "Leadership & Management",
            "Autobiography",
            "Personal Development",
            "Leadership & Management",
            "Technology",
            "Personal Development",
            "Engineering",
            "Engineering",
            "Engineering",
            "Engineering",
            "Engineering",
            "Engineering",
            "Personal Development",
            "Leadership & Management",
            "Personal Development",
            "Leadership & Management",
            "Marketing",
            "HR",
            "Leadership & Management",
            "Business",
            "Personal Development",
            "Personal Development",
            "Science",
            "Fiction",
            "Technology",
            "Engineering",
            "Engineering",
            "Business",
            "Engineering",
            "",
            "Leadership & Management",
            "",
            "",
            "",
            "",
            "HR",
            "Leadership & Management",
            "Business",
            "",
            "Novel",
            "Leadership & Management",
            "",
            "",
            "",
            "",
            "",
            "",
            "Leadership & Management",
            "",
            "",
            "",
            "",
            "Marketing",
            "HR",
            "",
            "Business",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Marketing",
            "",
            "Marketing",
            "Business",
            "Marketing",
            "Marketing",
            "",
            "Business",
            "Marketing",
            "",
            "",
            "",
            "",
            "Business",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Business",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Business",
            "",
            "",
            "",
            "",
            "",
            "Marketing",
            "Marketing",
            "",
            ""
        };

        string[] AmazonLinks = 
        {
            "https://www.amazon.com/Life-3-0-Being-Artificial-Intelligence/dp/1101946598",
            "https://www.amazon.com/Grokking-Algorithms-illustrated-programmers-curious/dp/1617292230",
            "https://www.amazon.com/Black-Swan-Improbable-Robustness-Fragility/dp/081297381X",
            "https://www.amazon.com/Read-People-like-Book-Charismatic/dp/B08R6H25BV/",
            "https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/B08X8ZXT15",
            "https://www.amazon.com/Algorithms-to-Live-By-audiobook/dp/B01D24NAL6",
            "https://www.amazon.com/Measure-What-Matters-Google-Foundation/dp/0525536221",
            "https://www.amazon.com/Traction-Get-Grip-Your-Business/dp/1936661837",
            "https://www.amazon.com/Empowered-Ordinary-People-Extraordinary-Products/dp/B08MV6VRGY",
            "https://www.amazon.com/Deep-Work-Cal-Newport-audiobook/dp/B0189PVAWY",
            "https://www.amazon.com/Emotional-Intelligence-2-0-Travis-Bradberry/dp/0974320625",
            "https://www.amazon.com/s?k=principles+by+ray+dalio&crid=BLYZ0SSI645N&sprefix=Principles+%2Caps%2C3913&ref=nb_sb_ss_ts-doa-p_1_11",
            "https://www.amazon.com/Extreme-Ownership-audiobook/dp/B015TM0RM4",
            "https://www.amazon.com/Profit-First-Mike-Michalowicz-audiobook/dp/B06X15WW79",
            "https://www.amazon.com/Actionable-Gamification-audiobook/dp/B06XSWX7BN",
            "https://www.amazon.com/Engineers-Survival-Guide-Facebook-Microsoft/dp/B09MBZBGFK",
            "https://www.amazon.com/Leading-Anywhere-Essential-Managing-Remote/dp/0358533279",
            "https://www.amazon.com/Long-Distance-Leader-Remarkable-Remote-Leadership/dp/1523094613",
            "https://www.amazon.com/Rocket-Fuel-audiobook/dp/B012HJOBRY",
            "https://www.amazon.com/Originals-audiobook/dp/B01A7Q61LI",
            "https://www.amazon.com/User-Story-Mapping-Discover-Product/dp/B08TZGKKF2",
            "https://www.amazon.com/Good-to-Great-Jim-Collins-audiobook/dp/B003VXI5MS",
            "https://www.amazon.com/Four-Obsessions-Extraordinary-Executive-Leadership/dp/B000079XXQ",
            "https://www.amazon.com/The-Miracle-Morning-Hal-Elrod-audiobook/dp/B00CLMX0D4",
            "https://www.amazon.com/Alone-Together-Expect-Technology-Other/dp/0465093655",
            "https://www.amazon.com/Start-with-Why-Simon-Sinek-audiobook/dp/B074VF6ZLM",
            "https://www.amazon.com/The-Infinite-Game-Simon-Sinek-audiobook/dp/B07DKHFTB7",
            "https://www.amazon.com/Think-Again-Power-Knowing-What/dp/B08HJQHNH9",
            "https://www.amazon.com/Find-Your-Why-audiobook/dp/B074F33DYD",
            "https://www.amazon.com/Blockchain-Wars-Future-Monopolies-Internet/dp/1736544101",
            "https://www.amazon.com/Trillion-Dollar-Coach-audiobook/dp/B07MVKGV9V",
            "https://www.amazon.com/Atomic-Habits-James-Clear-audiobook/dp/B07RFSSYBH",
            "https://www.amazon.com/Value-Proposition-Design-Customers-Strategyzer/dp/1118968050",
            "https://www.amazon.com/Outsourcing-All-You-Need-Know/dp/0992343615",
            "https://www.amazon.com/Get-Grip-Everything-Entrepreneurial-Business/dp/B01BITG25I",
            "https://www.amazon.com/Hooked-How-Build-Habit-Forming-Products/dp/B00HZY1N0K",
            "https://www.amazon.com/Financial-Intelligence-Revised-Managers-Knowing/dp/1422144119",
            "https://www.amazon.com/Psychology-Money-Timeless-Lessons-Happiness/dp/B08D9WJ9G8",
            "https://www.amazon.com/Smarter-Faster-Better-audiobook/dp/B017WRCV0A",
            "https://www.amazon.com/Continuous-Discovery-Habits-Discover-Products/dp/B09XYX49KX",
            "https://www.amazon.com/Contagious-Jonah-Berger-audiobook/dp/B00B91I8IK",
            "https://www.amazon.com/The-New-One-Minute-Manager-audiobook/dp/B00UVXZCPO",
            "https://www.amazon.com/Rework-Jason-Fried/dp/0307463745",
            "https://www.amazon.com/Blink-Malcolm-Gladwell-audiobook/dp/B00097DWY0",
            "https://www.amazon.com/Human-Compatible-Stuart-Russell-audiobook/dp/B07RLSGS2W",
            "https://www.amazon.com/Crucial-Conversations-Third-Talking-Stakes/dp/B09MV3818X",
            "https://www.amazon.com/Startup-CXO-Companys-Functions-Techstars-ebook/dp/B0949F83K5",
            "https://www.amazon.com/API-Design-Patterns-JJ-Geewax/dp/161729585X",
            "https://www.amazon.com/How-Take-Smart-Notes-Technique-ebook/dp/B09V5M8FR5/",
            "https://www.amazon.com/Blockchain-Wars-Future-Monopolies-Internet/dp/1736544101",
            "",
            "https://www.amazon.com/Book-Why-Science-Cause-Effect/dp/1541698967",
            "https://www.amazon.com/Designing-Data-Intensive-Applications-Reliable-Maintainable/dp/1449373321",
            "https://www.amazon.com/Vested-Outsourcing-Second-Rules-Transform/dp/1137297190",
            "https://www.amazon.com/Outliers-Story-Success-Malcolm-Gladwell/dp/0316017930",
            "https://www.amazon.com/Code-That-Fits-Your-Head/dp/0137464401",
            "https://www.amazon.com/No-Rules-Netflix-Culture-Reinvention/dp/B0845Z14DX",
            "https://www.amazon.com/What-Heck-is-EOS-audiobook/dp/B077Y32WD2",
            "https://www.amazon.com/Team-Building-Activities-Remote-Teams/dp/B08KQ1K2ZZ",
            "https://www.amazon.com/Head-First-Design-Patterns-Object-Oriented/dp/149207800X",
            "https://www.amazon.com/Breath-New-Science-Lost-Art/dp/B082FPZC4H",
            "https://www.amazon.com/Zero-to-One-audiobook/dp/B00M284NY2",
            "https://www.amazon.com/The-Phoenix-Project-audiobook/dp/B00VATFAMI",
            "https://www.amazon.com/Eat-That-Frog-Great-Procrastinating/dp/B08NN397DN",
            "https://www.amazon.com/Master-Your-Emotions-Practical-Negativity/dp/B07YLCK37V",
            "https://www.amazon.com/The-Perfect-Weapon-David-E-Sanger-audiobook/dp/B07B7QPYGZ",
            "https://www.amazon.com/Mans-Search-Meaning-Viktor-Frankl/dp/0807014273",
            "https://www.amazon.com/INSPIRED-Create-Tech-Products-Customers/dp/1119387507",
            "https://www.amazon.com/Audible-The-EOS-Life/dp/B09GTMMFNZ",
            "https://www.amazon.com/Spatial-Web-connect-machines-transform/dp/0578562960",
            "https://www.amazon.com/Influencing-Virtual-Teams-Tactics-Employees/dp/1530005140",
            "https://www.amazon.com/Merchants-Doubt-Handful-Scientists-Obscured/dp/1608193942",
            "https://www.amazon.com/48-Laws-Power-Robert-Greene/dp/0140280197",
            "https://www.amazon.com/The-Ride-of-Lifetime-Robert-Iger-audiobook/dp/B07QW2LHN4",
            "https://www.amazon.com/Leaders-Eat-Last-Together-Others/dp/B084D1NZGL",
            "https://www.amazon.com/The-Tipping-Point-audiobook/dp/B000OYD8T2",
            "https://www.amazon.com/The-Lean-Product-Playbook-audiobook/dp/B01FV5Y7MA",
            "https://www.amazon.com/Managers-Path-Leaders-Navigating-Growth/dp/1491973897",
            "https://www.amazon.com/Selling-Outsourcing-Services-Digital-Age/dp/0692139516",
            "https://www.amazon.com/Steve-Jobs-Walter-Isaacson-audiobook/dp/B07ZMKXMTG",
            "https://www.amazon.com/You-Are-Badass%C2%AE-Doubting-Greatness/dp/B088P8QL1N",
            "https://www.amazon.com/Dream-No-Little-Dreams-clayton-l-mathile-echo-m-garr/dp/1934282030",
            "https://www.amazon.com/INFLUENCE-CARNEGIE-Influence-Paperback-01-Oct-1998/dp/B004FQ18H4",
            "https://www.amazon.com/Intelligent-Investor-Definitive-Investing-Essentials/dp/0060555661",
            "https://www.amazon.com/Antifragile-Nassim-Nicholas-Taleb-audiobook/dp/B00A2ZIZYQ",
            "https://www.amazon.com/CHANGES-Professionals-Accomplishing-Mastering-Adaptability/dp/1733939709",
            "https://www.amazon.com/Blockchain-Revolution-Technology-Cryptocurrencies-Changing/dp/1101980141",
            "https://www.amazon.com/Learning-Domain-Driven-Design-Aligning-Architecture/dp/1098100131",
            "https://www.amazon.com/Elon-Musk-SpaceX-Fantastic-Future/dp/006230125X",
            "https://www.amazon.com/Selling-Outsourcing-Services-Collaborate-Infrastructure/dp/0578441586",
            "https://www.amazon.com/Metaverse-How-Will-Revolutionize-Everything/dp/B09T793GV9",
            "https://www.amazon.com/Pensar-rapido-pensar-despacio/dp/B085NZ4HVD",
            "https://www.amazon.com/12-Rules-for-Life-audiobook/dp/B0797Y87JC",
            "https://www.amazon.com/LinkedIn-Riches-John-Nemo-audiobook/dp/B00K1NA0CO",
            "https://www.amazon.com/Skin-Game-Hidden-Asymmetries-Daily/dp/042528462X",
            "https://www.amazon.com/Vivid-Vision-Remarkable-Aligning-Business/dp/B07S4PMS6P",
            "https://www.amazon.com/The-Fearless-Organization-audiobook/dp/B07Q33FMBY",
            "https://www.amazon.com/Who-Moved-My-Cheese-audiobook/dp/B07F7LS2ZW",
            "https://www.amazon.com/The-Bitcoin-Standard-audiobook/dp/B07D81VLQH",
            "https://www.amazon.com/Good-Code-Bad-Software-Engineer/dp/B09J6H5PPF",
            "https://www.amazon.com/The-Brain-David-Eagleman-audiobook/dp/B014L8XPF8",
            "https://www.amazon.com/Inside-Outsourcing-Offshoring-Employment-Changing-ebook/dp/B0B1YSBJ4H",
            "https://www.amazon.com/The-Laws-of-Human-Nature-audiobook/dp/B07DLDD46C",
            "https://www.amazon.com/Great-Gatsby-Original-Fitzgerald-Classic/dp/B093MYWTT5",
            "https://www.amazon.com/Five-Dysfunctions-of-Team-audiobook/dp/B000079XXR",
            "https://www.amazon.com/Why-We-Sleep-Matthew-Walker-audiobook/dp/B0752XRB5F",
            "https://www.amazon.com/Exactly-What-to-Say-Phil-M-Jones-audiobook/dp/B077ZDX69T",
            "https://www.amazon.com/Culture-Driven-Recruiting-Eliminate-Competition/dp/1641111631",
            "https://www.amazon.com/How-Great-Boss-Gino-Wickman/dp/1942952848",
            "https://www.amazon.com/Benjamin-Franklin-An-American-Life/dp/B004VLETYM",
            "https://www.amazon.com/Fooled-by-Randomness-audiobook/dp/B0012IZFRW",
            "https://www.amazon.com/Dare-to-Lead-Brene-Brown-audiobook/dp/B07DJYFLX8",
            "https://www.amazon.com/Bad-Blood-John-Carreyrou-audiobook/dp/B07BMCMS5L",
            "https://www.amazon.com/Habits-Highly-Effective-People-Anniversary/dp/B086DD5KSJ",
            "https://www.amazon.com/Patterns-Enterprise-Application-Architecture-Martin/dp/0321127420",
            "https://www.amazon.com/Cracking-Coding-Interview-Programming-Questions/dp/0984782850",
            "",
            "",
            "",
            "",
            "https://www.amazon.com/SUMMARY-Leading-Brain-Neuroscience-Friederike-ebook/dp/B09YYMKJCY",
            "https://www.amazon.com/Never-Split-Difference-Negotiating-Depended-ebook/dp/B014DUR7L2",
            "https://www.amazon.com/Getting-Things-Done-Stress-Free-Productivity-ebook/dp/B00KWG9M2E",
            "https://www.amazon.com/Scrum-Doing-Twice-Work-Half-ebook/dp/B00JI54HCU",
            "https://www.amazon.com/Building-StoryBrand-Clarify-Message-Customers-ebook/dp/B06XFJ2JGR",
            "https://www.amazon.com/Hire-Design-Hiring-Blueprint-Thinking-ebook/dp/B08J2MRNF7",
            "https://www.amazon.com/Who-Not-How-Accelerating-Teamwork-ebook/dp/B0867ZJ151",
            "https://www.amazon.com/Business-Model-Generation-Visionaries-Challengers/dp/0470876417",
            "https://www.amazon.com/Predictably-Irrational-Revised-Expanded-Decisions/dp/0061353248/",
            "https://www.amazon.com/How-Create-Mind-Thought-Revealed/dp/B09V1YC8FR/",
            "https://www.amazon.com/Factfulness-audiobook/dp/B07BFDCWZP/",
            "https://www.amazon.com/Homo-Deus-Yuval-Noah-Harari-audiobook/dp/B01MYZ4OUW/",
            "https://www.amazon.com/Superintelligence-Nick-Bostrom-audiobook/dp/B00LPMFE9Y/",
            "https://www.amazon.com/Clean-Architecture-Craftsmans-Software-Structure/dp/B08X8H5G2J/",
            "https://www.amazon.com/Refactoring-Improving-Existing-Addison-Wesley-Signature/dp/0134757599/",
            "https://www.amazon.com/The-Lean-Startup-Eric-Ries-audiobook/dp/B005MM7HY8/",
            "https://www.amazon.com/Fundamentals-Deep-Learning-Next-Generation-Intelligence/dp/149208218X",
            "https://www.amazon.com/Quiet-Power-Introverts-World-Talking/dp/0307352153/",
            "https://www.amazon.com/Process-Discipline-Consistency-Will-Business/dp/1637741367",
            "https://www.amazon.com/Unique-Ability%C2%AE-2-0-Discovery-Define/dp/1897239416/",
            "https://www.amazon.com/1984-Signet-Classics-George-Orwell/dp/0451524934/",
            "https://www.amazon.com/Give-Get-Employer-Branding-Belonging/dp/1544507062",
            "https://www.amazon.com/Powerful-Phrases-Dealing-Difficult-People/dp/0814432980/",
            "https://www.amazon.com/Talent-Chooses-You-Employer-Branding/dp/B089M1HVV6/",
            "https://www.amazon.com/Celebrity-CEO-Entrepreneurs-Building-Community-ebook/dp/B086N4H99S",
            "https://www.amazon.com/You-Are-Brand-Profitable-Personally/dp/B09N59PMHJ",
            "https://www.amazon.com/11-Laws-Likability-Relationship-Networking/dp/B083JLM4YF/",
            "https://www.amazon.com/Road-Wigan-Pier-George-Orwell/dp/0156767503/",
            "https://www.amazon.com/Handbook-Global-Outsourcing-Offshoring/dp/0230235506",
            "https://www.amazon.com/Mastermind-Dinners-Relationships-Connecting-Influencers/dp/0692360026",
            "https://www.amazon.com/Ask-Powerful-Questions-audiobook/dp/B07JKJRZNQ",
            "https://www.amazon.com/Giftology-John-Ruhlin-audiobook/dp/B01KVTN8A8",
            "https://www.amazon.com/Give-and-Take-Adam-M-Grant-PhD-audiobook/dp/B00BMBANYY",
            "https://www.amazon.com/Beyond-Order-More-Rules-Life/dp/B08P3R4CKJ/",
            "https://www.amazon.com/Never-Eat-Alone-Expanded-Updated/dp/B00M0VIA7W",
            "https://www.amazon.com/101-Tough-Conversations-Have-Employees/dp/1400212014",
            "https://www.amazon.com/LinkedIn-Personal-Branding-Ultimate-Guide/dp/B08VCQWRQ8",
            "https://www.amazon.com/Surrounded-Idiots-Behavior-Effectively-Communicate-ebook/dp/B07J4YT2HB",
            "https://www.amazon.com/BrandingPays-Five-Step-System-Reinvent-Personal/dp/098843752X/",
            "https://www.amazon.com/Nuts-Southwest-Airlines-Business-Personal/dp/0767901843",
            "https://www.amazon.com/The-1-Page-Marketing-Plan-audiobook/dp/B01KOQWSNQ",
            "https://www.amazon.com/Generation-Workplace-Workforce-Successful-Relationships/dp/0998638412/",
            "https://www.amazon.com/Sticking-Points-audiobook/dp/B01N49J5DP",
            "https://www.amazon.com/Small-Giants-Companies-Instead-10th-Anniversary/dp/014310960X",
            "https://www.amazon.com/Networking-Is-Not-Working-audiobook/dp/B00QJHXPJ6",
            "https://www.amazon.com/Risking-Viscott/dp/0671664093/",
            "https://www.amazon.com/Agile-Testing-Practical-Guide-Testers/dp/0321534468",
            "https://www.amazon.com/Software-Testing-Techniques-Boris-Beizer/dp/0442206720",
            "https://www.amazon.com/Software-Test-Automation-Mark-Fewster/dp/0201331403/",
            "https://www.amazon.com/How-Break-Software-Practical-Testing/dp/0201796198/",
            "https://www.amazon.com/Strategies-Wealth-Happiness-Americas-Philosopher/dp/0761506160",
            "https://www.amazon.com/SELL-LIKE-CRAZY-Customers-Possibly-ebook/dp/B07N7GRHNK",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "https://www.amazon.com/Gap-Selling-Problem-Centric-Everything-Relationships/dp/B07MD6PKRB",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        };
        
        for(int i = 0; i < BookNames.Length; i++)
        {
            Datas[i] = new BookData();
            Datas[i].Id = i + 1;
            Datas[i].BookName = BookNames[i];
            Datas[i].Author = Authors[i];
            Datas[i].FocusArea = BookTypes[i];
            Datas[i].AmazonLink = AmazonLinks[i];
        }
    }
}